"""Wiki page types, data models, and frontmatter conventions.

Wiki pages are LLM-compiled markdown files stored in the Obsidian vault.
They are 'compiled results' from source documents, not replacements.
"""

from dataclasses import dataclass, field

# Valid wiki page types (prefixed to avoid collision with user notes)
PAGE_TYPES = {
    "wiki_entity", "wiki_concept", "wiki_source", "wiki_analysis", "wiki_question",
}

# Frontmatter field names
FM_TYPE = "type"
FM_TITLE = "title"
FM_TAGS = "tags"
FM_SOURCES = "sources"
FM_SOURCE_HASH = "source_hash"
FM_GENERATED_BY = "generated_by"
FM_CREATED = "created"
FM_UPDATED = "updated"
FM_SOURCE_REFS = "source_refs"

GENERATED_BY = "bobodan"


@dataclass
class WikiPage:
    """A single wiki page generated by the compiler."""
    title: str
    page_type: str           # wiki_entity | wiki_concept
    content: str             # markdown body (不含 frontmatter)
    tags: list[str] = field(default_factory=list)
    sources: list[str] = field(default_factory=list)   # 原始资料路径
    links: list[str] = field(default_factory=list)      # wikilink 目标
    source_refs: list[dict] = field(default_factory=list)
    source_hash: str = ""    # 源文件 SHA-256，用于增量更新
    indexable: bool = True   # True=可被 /kb sync 索引
    created: str = ""
    updated: str = ""
    summary: str = ""
    schema_version: int = 1
    status: str = "active"

    def to_markdown(self) -> str:
        """Serialize to markdown with YAML frontmatter."""
        import yaml
        from datetime import datetime, timezone

        now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        meta = {
            FM_TYPE: self.page_type,
            FM_TITLE: self.title,
            "summary": self.summary,
            "schema_version": self.schema_version,
            FM_GENERATED_BY: GENERATED_BY,
            FM_TAGS: self.tags or [],
            FM_SOURCES: self.sources or [],
            FM_SOURCE_REFS: self.source_refs or [],
            FM_SOURCE_HASH: self.source_hash,
            "indexable": self.indexable,
            "status": self.status,
            FM_CREATED: self.created or now,
            FM_UPDATED: now,
        }
        fm = yaml.dump(meta, allow_unicode=True, default_flow_style=False).strip()
        return f"---\n{fm}\n---\n\n# {self.title}\n\n{self.content.strip()}\n"


@dataclass
class CompileResult:
    """Result of compiling one or more source files."""
    pages: list[WikiPage] = field(default_factory=list)
    entities_count: int = 0
    concepts_count: int = 0
    sources_count: int = 0
    errors: list[dict] = field(default_factory=list)
    skipped: list[str] = field(default_factory=list)  # 未变更的源文件


@dataclass
class WikiConfig:
    """Wiki directory configuration."""
    wiki_dir: str = "wiki"           # vault 内相对路径
    entity_dir: str = "entities"
    concept_dir: str = "concepts"
    source_dir: str = "sources"
    analysis_dir: str = "analyses"
    question_dir: str = "questions"
    template_dir: str = "templates"

    def entities_path(self, vault_path: str) -> str:
        import os
        return os.path.join(vault_path, self.wiki_dir, self.entity_dir)

    def concepts_path(self, vault_path: str) -> str:
        import os
        return os.path.join(vault_path, self.wiki_dir, self.concept_dir)

    def sources_path(self, vault_path: str) -> str:
        import os
        return os.path.join(vault_path, self.wiki_dir, self.source_dir)

    def analyses_path(self, vault_path: str) -> str:
        import os
        return os.path.join(vault_path, self.wiki_dir, self.analysis_dir)

    def questions_path(self, vault_path: str) -> str:
        import os
        return os.path.join(vault_path, self.wiki_dir, self.question_dir)

    def page_path(self, vault_path: str, page_type: str) -> str:
        mapping = {
            "wiki_source": self.sources_path,
            "wiki_entity": self.entities_path,
            "wiki_concept": self.concepts_path,
            "wiki_analysis": self.analyses_path,
            "wiki_question": self.questions_path,
        }
        if page_type not in mapping:
            raise ValueError(f"Unsupported Wiki page type: {page_type}")
        return mapping[page_type](vault_path)

    def page_dirs(self) -> tuple[str, ...]:
        return (
            self.source_dir, self.entity_dir, self.concept_dir,
            self.analysis_dir, self.question_dir,
        )

    def index_path(self, vault_path: str) -> str:
        import os
        return os.path.join(vault_path, self.wiki_dir, "index.md")

    def log_path(self, vault_path: str) -> str:
        import os
        return os.path.join(vault_path, self.wiki_dir, "log.md")

    def registry_path(self, vault_path: str) -> str:
        """Path to source registry (replaces wiki/sources/ directory)."""
        import os
        return os.path.join(vault_path, self.wiki_dir, "source_registry.json")

    def state_path(self, vault_path: str) -> str:
        """Path to wiki state file for incremental tracking."""
        import os
        return os.path.join(vault_path, self.wiki_dir, ".wiki_state.json")


def load_wiki_state(vault_path: str, config: WikiConfig | None = None) -> dict:
    """Load wiki state (source hashes, page mappings). Returns {} if not found."""
    import json
    import os
    config = config or WikiConfig()
    path = config.state_path(vault_path)
    if not os.path.exists(path):
        return {}
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_wiki_state(vault_path: str, state: dict, config: WikiConfig | None = None) -> None:
    """Save wiki state."""
    import json
    import os
    config = config or WikiConfig()
    path = config.state_path(vault_path)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(state, f, ensure_ascii=False, indent=2)


def load_source_registry(vault_path: str, config: WikiConfig | None = None) -> dict:
    """Load source registry. Returns {source_path: {hash, pages, updated}}."""
    import json
    import os
    config = config or WikiConfig()
    path = config.registry_path(vault_path)
    if not os.path.exists(path):
        return {}
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def save_source_registry(vault_path: str, registry: dict, config: WikiConfig | None = None) -> None:
    """Save source registry."""
    import json
    import os
    config = config or WikiConfig()
    path = config.registry_path(vault_path)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(registry, f, ensure_ascii=False, indent=2)
